### ISSUE TITLE
Cannot read file

### ISSUE THREAD

**Issue by sqrt-panda** [Mixaz017/FortGameUserSettings-Editor#1]
I get an error when I start up.
![image](https://user-images.githubusercontent.com/39018125/55233024-91f0d000-526a-11e9-9b19-ba64536aebf6.png)

**Comment by Mixaz017** [comment]
Please tell me the full path of GameUserSettings.ini. I will fix it in the next release.

**Comment by sqrt-panda** [comment]
GameUserSettings.ini's full path is "C:\Users\panda\AppData\Local\FortniteGame\Saved\Config\WindowsClient\GameUserSettings.ini"
I think this path is the default.

**Comment by Mixaz017** [comment]
I can not reproduce the problem.
I renamed my GameUserSettings.ini and let Fortnite re-create it automatically, but the program can read the re-created file well.
Please check your GameUserSettings.ini as it may be corrupted.

**Comment by sqrt-panda** [comment]
I found the cause.
GameUserSetting.ini is saved in UTF-16 BOM when use Fortnite in Japanese and set the sound tab.
So this application can not read this ini.

**Comment by Mixaz017** [comment]
Thanks for Information, I will fix it

**Comment by Mixaz017** [comment]
Updated release, now this program detects encoding

**Comment by sqrt-panda** [comment]
thx! now, I can edit setting.
